from connect_database import Connect
db = Connect()

try:
    with db as conn:
        with conn:
            with conn.cursor() as curs:
                curs.execute('SELECT * FROM books;')
                books = curs.fetchall()
                for book in books:
                    print(book)
                #
                # curs.execute('SELECT * FROM publishers;')
                # pubs = curs.fetchall()
                # for pub in pubs:
                #     print(pub)
                #
                # min_stock = int(input("search for minimum stock: "))
                #
                # curs.execute('SELECT title FROM books WHERE stock_quantity <= %s;', (min_stock,))
                # query_res = curs.fetchall()
                # for row in query_res:
                #     print(row)
                # curs.execute('SELECT books.title, publishers.pub_name '
                #              'FROM books '
                #              'LEFT JOIN publishers ON books.publisher_id = publishers.pub_id;')
                # query_res = curs.fetchall()
                # for title, pub_name in query_res:
                #     # Handling the 'None' value for books without a publisher
                #     display_pub = pub_name if pub_name else "Independent / Unknown"
                #     print(f"Book: {title} | Publisher: {display_pub}")

                # curs.execute('INSERT INTO books(book_id,title,author,genre,price, stock_quantity, publisher_id) VALUES (%s, %s, %s, %s, %s, %s, %s);',
                #              (6,'Project Hail Mary', 'Andy Weir', 'Sci-Fi', 18.00, 10, 102))
                #
                # conn.commit() # NO LONGER NEEDED if using with conn:

                # WE ARE TO SET THE PRIMARY KEYS AS AUTO INCREMENT

                # curs.execute('ALTER TABLE books '
                #              'ALTER COLUMN book_id ADD GENERATED BY DEFAULT AS IDENTITY')
                # curs.execute("SELECT setval(pg_get_serial_sequence('books', 'book_id'),"
                #              "(SELECT MAX(book_id) FROM books));")

                # curs.execute('INSERT INTO books(title,author,genre,price, stock_quantity, publisher_id) VALUES (%s, %s, %s, %s, %s, %s) RETURNING book_id;;',
                #              ('Algorithms', 'Alex Su', 'Technology', 28.00, 2, 102))
                # new_id = curs.fetchone()[0]
                # print(f"Successfully inserted! The new book ID is: {new_id}")
except Exception as e:
    print(f"An error occurred during database operation: {e}")